import { getSession, useSession } from 'next-auth/react';
import Head from 'next/head';
import Header from '../components/Header';
import Login from '../components/Login';
import Sidebar from '../components/Sidebar';
import { signIn } from '../features/auth/google';
import Feed from '../components/Feed';
import Widgets from '../components/Widgets';

const Home = () => {
  return (
    <div className='h-screen bg-gray-100 overflow-hidden'>
      <Head>
        <title>Facebook</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/f_logo_RGB-Blue_72.png' />
      </Head>

      <Header />

      <main className='flex'>
        <Sidebar />
        <Feed />
        <Widgets />
      </main>
    </div>
  );
};
export default Home;
